[package]
name = "statemachine"
version = "0.1.0"
authors = ["Taylor Thomas <taylor.thomas@microsoft.com>"]
edition = "2018"

[dependencies]
petgraph = "0.5"
anyhow = "1.0"
dashmap = "4.0.0-rc6"
tokio = { version = "0.2", features = ["sync", "macros", "signal", "rt-core"] }
